// <auto-generated />
using System;
using KolokwiumAPBD2.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KolokwiumAPBD2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KolokwiumAPBD2.Models.BackPackSlot", b =>
                {
                    b.Property<int>("BackPackSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BackPackSlotId"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("FK_character");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("FK_item");

                    b.HasKey("BackPackSlotId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("Backpack_Slotss");

                    b.HasData(
                        new
                        {
                            BackPackSlotId = 1,
                            CharacterId = 1,
                            ItemId = 1
                        },
                        new
                        {
                            BackPackSlotId = 2,
                            CharacterId = 2,
                            ItemId = 2
                        });
                });

            modelBuilder.Entity("KolokwiumAPBD2.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int")
                        .HasColumnName("current_weig");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int")
                        .HasColumnName("max_weight");

                    b.Property<int>("Money")
                        .HasColumnType("int")
                        .HasColumnName("money");

                    b.HasKey("CharacterId");

                    b.ToTable("Characterss");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            CurrentWeight = 10,
                            FirstName = "Gerald",
                            LastName = "Z Rivii",
                            MaxWeight = 300,
                            Money = 100
                        },
                        new
                        {
                            CharacterId = 2,
                            CurrentWeight = 69,
                            FirstName = "Szczur",
                            LastName = "Mysiur",
                            MaxWeight = 250,
                            Money = 200
                        });
                });

            modelBuilder.Entity("KolokwiumAPBD2.Models.CharacterTitle", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("FK_charact");

                    b.Property<int>("TitleId")
                        .HasColumnType("int")
                        .HasColumnName("FK_title");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("aquire_at");

                    b.HasKey("CharacterId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("Characters_Titless");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            TitleId = 1,
                            AcquiredAt = new DateTime(2024, 6, 14, 12, 20, 7, 26, DateTimeKind.Local).AddTicks(9329)
                        },
                        new
                        {
                            CharacterId = 2,
                            TitleId = 2,
                            AcquiredAt = new DateTime(2024, 6, 14, 12, 20, 7, 29, DateTimeKind.Local).AddTicks(2577)
                        });
                });

            modelBuilder.Entity("KolokwiumAPBD2.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weig");

                    b.HasKey("ItemId");

                    b.ToTable("Itemss");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Name = "Miecz połksiezyca",
                            Weight = 2
                        },
                        new
                        {
                            ItemId = 2,
                            Name = "Sierp drwala",
                            Weight = 1
                        });
                });

            modelBuilder.Entity("KolokwiumAPBD2.Models.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TitleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nam");

                    b.HasKey("TitleId");

                    b.ToTable("Titless");

                    b.HasData(
                        new
                        {
                            TitleId = 1,
                            Name = "Rycerz"
                        },
                        new
                        {
                            TitleId = 2,
                            Name = "Mag"
                        });
                });

            modelBuilder.Entity("KolokwiumAPBD2.Models.BackPackSlot", b =>
                {
                    b.HasOne("KolokwiumAPBD2.Models.Character", "Character")
                        .WithMany("BackPackSlots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KolokwiumAPBD2.Models.Item", "Item")
                        .WithMany("BackPackSlots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("KolokwiumAPBD2.Models.CharacterTitle", b =>
                {
                    b.HasOne("KolokwiumAPBD2.Models.Character", "Character")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KolokwiumAPBD2.Models.Title", "Title")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("KolokwiumAPBD2.Models.Character", b =>
                {
                    b.Navigation("BackPackSlots");

                    b.Navigation("CharacterTitles");
                });

            modelBuilder.Entity("KolokwiumAPBD2.Models.Item", b =>
                {
                    b.Navigation("BackPackSlots");
                });

            modelBuilder.Entity("KolokwiumAPBD2.Models.Title", b =>
                {
                    b.Navigation("CharacterTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
